DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user TEXT NOT NULL,
	password  TEXT NOT NULL,
	role TEXT NOT NULL
);
